import type { Vehicle, BlogPost } from "~/types";

export const VEHICLES: Vehicle[] = [
  {
    id: "mercedes-benz-s-class",
    name: "Mercedes-Benz S-Class",
    type: "Sedan",
    brand: "Mercedes-Benz",
    price: 3500000000,
    year: 2026,
    fuel: "Hybrid",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800",
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=800",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
    ],
    tags: ["Baru"],
    description: [
      "Mercedes-Benz S-Class mendefinisikan ulang kemewahan otomotif modern dengan keanggunan yang tiada tara dan kenyamanan luar biasa. Setiap lekukan eksterior dan setiap detail interior dirancang untuk memanjakan indra Anda, memberikan pengalaman berkendara yang tenang dan berwibawa.",
      "Didukung oleh teknologi mesin hybrid canggih, kendaraan ini menggabungkan efisiensi bahan bakar yang optimal dengan performa dinamis yang halus. Keamanan kelas dunia dan sistem hiburan MBUX terbaru memastikan Anda tetap terhubung dan terlindungi di setiap perjalanan.",
    ],
    specs: {
      engine: "3.0L Inline-6 Turbo Hybrid",
      fuelConsumption: "12.5 km/Liter",
      horsePower: "429 hp",
      driveSystem: "All-Wheel Drive (4MATIC)",
      transmission: "9-Speed Automatic",
      acceleration: "4.9 Detik",
    },
  },
  {
    id: "bmw-5-series",
    name: "BMW 5 Series",
    type: "Sedan",
    brand: "BMW",
    price: 1400000000,
    year: 2026,
    fuel: "Hybrid",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800",
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=800",
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?q=80&w=800",
    ],
    tags: [],
    description: [
      "BMW 5 Series menggabungkan kecerdasan sporty dengan estetika eksekutif yang prestisius. Sedan legendaris ini dirancang untuk mereka yang menuntut dinamika berkendara yang tajam dipadukan dengan kenyamanan kabin kelas bisnis.",
      "Sistem mild-hybrid yang disematkan memberikan dorongan instan yang halus sekaligus menekan emisi gas buang. Interior futuristik dengan BMW Curved Display menghadirkan era baru digitalisasi di ujung jari Anda.",
    ],
    specs: {
      engine: "2.0L TwinPower Turbo 4-Cylinder Hybrid",
      fuelConsumption: "14.2 km/Liter",
      horsePower: "255 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "8-Speed Automatic",
      acceleration: "5.9 Detik",
    },
  },
  {
    id: "audi-a6",
    name: "Audi A6",
    type: "Sedan",
    brand: "Audi",
    price: 1200000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=800",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?q=80&w=800",
    ],
    tags: ["Promo"],
    description: [
      "Audi A6 adalah simbol kecerdasan dan kemajuan teknologi Jerman. Desainnya yang presisi mengekspresikan karakter dinamis yang kuat, sementara kabin virtual cockpit-nya menghadirkan pengalaman kontrol digital penuh.",
      "Dengan sistem penggerak legendaris quattro, mobil ini mencengkeram jalanan dengan mantap dalam kondisi cuaca apa pun. Kenyamanan berkendara dioptimalkan secara dinamis melalui suspensi adaptif pintar.",
    ],
    specs: {
      engine: "2.0L TFSI 4-Cylinder",
      fuelConsumption: "13.8 km/Liter",
      horsePower: "248 hp",
      driveSystem: "All-Wheel Drive (quattro)",
      transmission: "7-Speed S-tronic",
      acceleration: "6.2 Detik",
    },
  },
  {
    id: "elegance-series-9",
    name: "Elegance Series 9",
    type: "Sedan",
    brand: "BMW",
    price: 2450000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800",
    ],
    tags: ["Baru"],
    description: [
      "Elegance Series 9 merupakan puncak dari filosofi keanggunan berkendara. Didesain secara eksklusif dengan proporsi bodi yang agung dan interior berlapis kulit Nappa pilihan terbaik, mobil ini memancarkan status sosial yang luhur.",
      "Mesin V6 Twin-Turbocharged miliknya menghadirkan tenaga yang melimpah namun tetap senyap. Sistem peredam kabin aktif menyaring seluruh kebisingan luar, menciptakan suaka keheningan pribadi bagi penumpangnya.",
    ],
    specs: {
      engine: "3.0L V6 Twin-Turbo",
      fuelConsumption: "11.0 km/Liter",
      horsePower: "380 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "8-Speed Automatic",
      acceleration: "5.2 Detik",
    },
  },
  {
    id: "summit-suv-x",
    name: "Summit SUV X",
    type: "SUV",
    brand: "Mercedes-Benz",
    price: 3120000000,
    year: 2026,
    fuel: "Hybrid",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=800",
    ],
    tags: [],
    description: [
      "Summit SUV X adalah SUV flagship mewah yang memadukan kapabilitas off-road ekstrem dengan kemegahan kabin layaknya jet pribadi. Menawarkan konfigurasi 7-kursi dengan ruang yang lapang di setiap baris.",
      "Sistem suspensi udara canggih mampu membaca kontur jalanan secara real-time untuk menyesuaikan kelembutan redaman. Dapatkan ketenangan pikiran mutlak dengan paket asisten berkendara semi-otonom terlengkap.",
    ],
    specs: {
      engine: "3.0L Inline-6 Turbo Hybrid",
      fuelConsumption: "10.5 km/Liter",
      horsePower: "362 hp",
      driveSystem: "All-Wheel Drive (4MATIC)",
      transmission: "9-Speed Automatic",
      acceleration: "5.6 Detik",
    },
  },
  {
    id: "volt-gt-pro",
    name: "Volt GT Pro",
    type: "Electric",
    brand: "Audi",
    price: 1950000000,
    year: 2026,
    fuel: "Listrik",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=800",
      "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=800",
    ],
    tags: ["Elektrik"],
    description: [
      "Volt GT Pro membawa Anda melompat ke masa depan mobilitas berkinerja tinggi. Mobil sport listrik murni ini memadukan aerodinamika agresif dengan arsitektur kelistrikan 800V untuk pengisian daya ultra-cepat.",
      "Akselerasi instan tanpa jeda dari motor listrik ganda melontarkan Anda bagai peluru. Dilengkapi dengan interior ramah lingkungan berbasis material daur ulang premium tanpa mengorbankan nuansa kemewahan.",
    ],
    specs: {
      engine: "Dual Electric Motors (800V)",
      fuelConsumption: "5.2 km/kWh",
      horsePower: "530 hp",
      driveSystem: "All-Wheel Drive (e-quattro)",
      transmission: "Single-Speed Automatic",
      acceleration: "3.5 Detik",
    },
  },
  {
    id: "apex-carrera",
    name: "Apex Carrera",
    type: "Sedan",
    brand: "Porsche",
    price: 4200000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Manual",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800",
    ],
    tags: [],
    description: [
      "Apex Carrera adalah perayaan murni bagi para pecinta adrenalin berkendara sejati. Mengusung mesin boxer legendaris di bagian belakang bodi, mobil sport ini menghantarkan sensasi berkendara mekanis yang sangat presisi.",
      "Transmisi manual 7-percepatan memberikan kontrol mutlak di tangan Anda. Didesain secara aerodinamis dengan sayap belakang adaptif yang meningkatkan downforce saat melibas tikungan sirkuit berkecepatan tinggi.",
    ],
    specs: {
      engine: "3.0L Twin-Turbo Flat-6 Boxer",
      fuelConsumption: "9.8 km/Liter",
      horsePower: "443 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "7-Speed Manual",
      acceleration: "4.0 Detik",
    },
  },
  {
    id: "elegance-series-7",
    name: "Elegance Series 7",
    type: "Sedan",
    brand: "BMW",
    price: 1850000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=800",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800",
    ],
    tags: [],
    description: [
      "Elegance Series 7 adalah jembatan sempurna antara kenyamanan berkendara sehari-hari dengan kemewahan eksekutif yang kokoh. Dibekali mesin tangguh berkekuatan tinggi serta kemudi aktif roda belakang yang mempermudah manuver perkotaan.",
      "Sistem suspensi adaptif cerdasnya mereduksi guncangan jalanan berlubang dengan sangat baik. Ruang interiornya dipenuhi dengan kokpit digital termutakhir dan tata suara surround tiga dimensi.",
    ],
    specs: {
      engine: "2.0L TwinPower Turbo 4-Cylinder",
      fuelConsumption: "13.0 km/Liter",
      horsePower: "258 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "8-Speed Automatic",
      acceleration: "6.1 Detik",
    },
  },
  {
    id: "summit-suv-v",
    name: "Summit SUV V",
    type: "SUV",
    brand: "Mercedes-Benz",
    price: 2100000000,
    year: 2026,
    fuel: "Hybrid",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=800",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
    ],
    tags: [],
    description: [
      "Summit SUV V mendefinisikan ulang utilitas perkotaan yang serbaguna dan dinamis. Menawarkan desain eksterior kokoh berpadu dengan kabin ramah keluarga yang sangat lapang dan fleksibel.",
      "Sistem hybrid bertenaga tinggi memberikan respons gas instan yang bertenaga namun ramah lingkungan. Dilengkapi kamera 360 derajat dan radar parkir cerdas untuk navigasi yang mudah di area sempit.",
    ],
    specs: {
      engine: "2.0L Turbo 4-Cylinder Hybrid",
      fuelConsumption: "11.8 km/Liter",
      horsePower: "255 hp",
      driveSystem: "All-Wheel Drive (4MATIC)",
      transmission: "9-Speed Automatic",
      acceleration: "6.9 Detik",
    },
  },
  {
    id: "volt-sedan-s",
    name: "Volt Sedan S",
    type: "Electric",
    brand: "Audi",
    price: 1450000000,
    year: 2026,
    fuel: "Listrik",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=800",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?q=80&w=800",
    ],
    tags: [],
    description: [
      "Volt Sedan S menghadirkan kemewahan berkendara bertenaga listrik murni untuk kebutuhan harian profesional perkotaan. Menawarkan daya jelajah baterai yang sangat impresif hingga 550 kilometer dalam sekali pengisian penuh.",
      "Kabin minimalis modern berfokus pada kedamaian pikiran pengendara dengan dasbor bebas tombol fisik dan kontrol suara AI yang responsif. Akselerasi super tenang memberikan sensasi rileks sepanjang perjalanan.",
    ],
    specs: {
      engine: "Single Electric Motor (400V)",
      fuelConsumption: "6.1 km/kWh",
      horsePower: "300 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "Single-Speed Automatic",
      acceleration: "5.5 Detik",
    },
  },
  {
    id: "apex-rs",
    name: "Apex RS",
    type: "Sedan",
    brand: "Porsche",
    price: 3800000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Manual",
    image:
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
    ],
    tags: [],
    description: [
      "Apex RS dikembangkan langsung dari lintasan balap sirkuit untuk legalitas jalanan umum. Setiap komponen bodi diperhitungkan secara ekstrem menggunakan serat karbon super ringan untuk mereduksi bobot secara drastis.",
      "Suara menggelegar dari knalpot titanium dan putaran mesin bensin atmosferik (naturally-aspirated) yang menyentuh 9.000 rpm menghadirkan pengalaman balap orisinal yang tidak akan Anda temukan di mobil lain.",
    ],
    specs: {
      engine: "4.0L Naturally Aspirated Flat-6",
      fuelConsumption: "8.5 km/Liter",
      horsePower: "502 hp",
      driveSystem: "Rear-Wheel Drive",
      transmission: "6-Speed Manual GT",
      acceleration: "3.2 Detik",
    },
  },
  {
    id: "2026-luxury-suv",
    name: "2026 Luxury SUV",
    type: "SUV",
    brand: "Mercedes-Benz",
    price: 1350000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Otomatis",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=800",
    ],
    tags: ["Baru"],
    description: [
      "Rasakan puncak teknik otomotif dengan Luxury SUV 2026. Dirancang untuk pengemudi cerdas yang menuntut performa luar biasa dan kenyamanan tanpa kompromi, kendaraan ini merupakan lompatan maju dalam desain modern dan integrasi teknologi. Garis eksterior yang berani menarik perhatian, sementara interior yang dibuat dengan cermat menyediakan tempat perlindungan dari material premium dan antarmuka yang intuitif.",
      "Di balik kapnya, powertrain yang disempurnakan menghasilkan akselerasi yang mudah, diseimbangkan oleh sistem suspensi canggih yang memastikan berkendara mulus di medan apa pun. Keselamatan adalah yang utama, dengan rangkaian lengkap fitur bantuan pengemudi aktif yang memberikan ketenangan pikiran di setiap perjalanan.",
    ],
    specs: {
      engine: "3.0L Twin-Turbo V6",
      fuelConsumption: "21 Kota / 28 Tol",
      horsePower: "375 hp",
      driveSystem: "All-Wheel Drive (AWD)",
      transmission: "8-Speed Automatic",
      acceleration: "5.2 Detik",
    },
  },
  {
    id: "ducati-panigale-v4",
    name: "Ducati Panigale V4 S",
    type: "Motor",
    brand: "Ducati",
    price: 850000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Manual",
    image:
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800",
      "https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?q=80&w=800",
    ],
    tags: ["Baru"],
    description: [
      "Ducati Panigale V4 S adalah ekspresi balap murni roda dua yang lahir langsung dari ajang balap dunia MotoGP. Mengusung mesin Desmosedici Stradale V4 berkapasitas 1.103 cc yang mampu melontarkan tenaga buas khas Ducati.",
      "Dilengkapi dengan suspensi elektronik Ohlins pintar, velg aluminium forged super ringan, dan paket aerodinamika winglet serat karbon untuk stabilitas pengereman luar biasa di kecepatan tinggi.",
    ],
    specs: {
      engine: "1,103 cc Desmosedici Stradale V4",
      fuelConsumption: "14.5 km/Liter",
      horsePower: "210 hp",
      driveSystem: "Chain Drive",
      transmission: "6-Speed Manual with DQS",
      acceleration: "2.9 Detik",
    },
  },
  {
    id: "bmw-s1000rr",
    name: "BMW S1000RR",
    type: "Motor",
    brand: "BMW",
    price: 790000000,
    year: 2026,
    fuel: "Bensin",
    transmission: "Manual",
    image:
      "https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?q=80&w=800",
    images: [
      "https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?q=80&w=800",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?q=80&w=800",
    ],
    tags: ["Promo"],
    description: [
      "BMW S1000RR adalah superbike berteknologi mutakhir Jerman yang dirancang untuk performa tanpa kompromi baik di jalan raya maupun sirkuit balap. Menawarkan kendali tak tertandingi berkat fitur elektronik asisten berkendara terlengkap.",
      "Sistem katup variabel BMW ShiftCam meningkatkan torsi di putaran mesin rendah sekaligus memberikan daya pacu luar biasa di putaran atas. Panel instrumen TFT 6.5 inci menampilkan navigasi dan visualisasi balapan yang mewah.",
    ],
    specs: {
      engine: "999 cc Oil/Water-Cooled Inline 4-Cylinder",
      fuelConsumption: "15.4 km/Liter",
      horsePower: "205 hp",
      driveSystem: "Chain Drive",
      transmission: "6-Speed Manual with Shift Assistant Pro",
      acceleration: "3.1 Detik",
    },
  },
];

export const BLOGS: BlogPost[] = [
  {
    id: "mobil-listrik-vs-bensin-2026",
    title: "Mobil Listrik vs Bensin: Mana yang Cocok untuk Anda di 2026?",
    excerpt:
      "Debat antara kendaraan listrik dan mesin pembakaran internal terus berlanjut. Kami menganalisis biaya kepemilikan, kemudahan pengisian daya, dan performa nyata keduanya.",
    content: [
      "Memasuki tahun 2026, pilihan antara membeli mobil listrik murni (EV) atau tetap menggunakan mobil bermesin bensin konvensional (ICE) menjadi keputusan yang semakin membingungkan bagi banyak calon pembeli. Kedua teknologi ini memiliki kelebihan dan kekurangan yang sangat signifikan tergantung pada kebutuhan mobilitas Anda.",
      "Dari sisi biaya operasional, mobil listrik jelas memimpin. Biaya pengisian daya listrik per kilometer jauh lebih murah dibandingkan dengan membeli bensin premium di Indonesia. Selain itu, pajak tahunan EV diuntungkan dengan subsidi pemerintah yang menjadikannya sangat murah. Namun, biaya investasi awal pembelian mobil listrik masih relatif lebih tinggi daripada mobil bensin sekelasnya.",
      "Bagi Anda yang sering bepergian ke luar kota dengan rute yang panjang, mobil bensin masih menawarkan kepraktisan yang belum bisa ditandingi. Infrastruktur SPBU tersebar merata hingga ke daerah terpencil, dan proses pengisian bahan bakar hanya memakan waktu kurang dari 5 menit. Sementara itu, infrastruktur SPKLU untuk mobil listrik terus berkembang pesat, namun Anda masih perlu merencanakan perjalanan dengan matang agar terhindar dari kehabisan daya.",
      "Kesimpulannya, jika mobilitas harian Anda didominasi di dalam kota besar dengan jarak tempuh di bawah 100 kilometer sehari, mobil listrik adalah pilihan investasi cerdas jangka panjang yang sangat hemat. Namun, jika Anda memerlukan fleksibilitas tanpa batas untuk perjalanan jarak jauh instan tanpa antrean pengisian daya, mobil bensin atau tipe hybrid masih menjadi pilihan teraman saat ini.",
    ],
    category: "Mobil Listrik",
    date: "May 15, 2026",
    author: "Admin Sentraoto",
    image:
      "https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=800",
    readTime: "5 Menit Baca",
  },
  {
    id: "tips-merawat-mesin-mobil-prima",
    title: "Tips Merawat Mesin Mobil Agar Tetap Prima",
    excerpt:
      "Perawatan preventif adalah kunci umur panjang kendaraan. Pelajari jadwal servis esensial dan tanda-tanda peringatan dini kerusakan mesin Anda.",
    content: [
      "Mesin mobil adalah jantung utama yang menentukan keselamatan dan kenyamanan perjalanan Anda. Merawat mesin agar selalu dalam kondisi prima tidak hanya mencegah mogok di tengah jalan, tetapi juga menjaga nilai jual kembali mobil Anda tetap tinggi.",
      "Langkah paling fundamental adalah penggantian oli mesin secara berkala. Oli berfungsi sebagai pelumas yang mencegah gesekan langsung logam antar-komponen mesin serta membantu mendinginkan suhu dalam silinder. Pastikan Anda mengganti oli dan filter oli sesuai dengan rekomendasi pabrikan, biasanya setiap 5.000 hingga 10.000 kilometer.",
      "Selain oli, perhatikan juga sistem pendingin mesin (radiator). Kebocoran kecil atau air radiator yang habis dapat menyebabkan mesin mengalami overheat yang berakibat pada kerusakan fatal silinder mesin yang memerlukan turun mesin berbiaya sangat mahal. Selalu cek volume air radiator cadangan (reservoir) setidaknya seminggu sekali.",
      'Terakhir, jangan abaikan lampu indikator "Check Engine" pada dasbor Anda. Begitu lampu ini menyala, segera bawa kendaraan Anda ke bengkel resmi Sentraoto untuk dilakukan pemindaian diagnostik komputer (obd scanner) guna mendeteksi komponen sensorik mana yang mulai mengalami malfungsi sebelum merembet ke kerusakan mekanis yang lebih serius.',
    ],
    category: "Tips & Trik",
    date: "May 10, 2026",
    author: "Yuda Pratama",
    image:
      "https://images.unsplash.com/photo-1486006920555-c77dce18193b?q=80&w=800",
    readTime: "4 Menit Baca",
  },
  {
    id: "review-lengkap-suv-premium-2026",
    title: "Review Lengkap SUV Premium Terbaru 2026",
    excerpt:
      "Kami menguji langsung jajaran SUV kelas atas tahun ini. Dari kenyamanan kabin hingga performa off-road, temukan mana yang layak menyandang gelar raja jalanan.",
    content: [
      "Segmen SUV mewah kelas atas terus memanas dengan hadirnya penyegaran model dari berbagai produsen raksasa Eropa. Kami berkesempatan menguji jajaran model terbaru ini untuk menilai aspek kenyamanan kabin, respons kemudi, teknologi suspensi, serta kapabilitas off-road sesungguhnya.",
      "Dalam pengujian jalan raya, kenyamanan suspensi udara adaptif menjadi sorotan utama. Sistem suspensi ini mampu membaca kondisi aspal di depan kendaraan dan melakukan penyesuaian kekerasan peredaman dalam hitungan milidetik. Hasilnya, kabin terasa sangat tenang bagaikan melayang di atas karpet terbang, bahkan saat melintasi jalanan berbatu atau bergelombang.",
      "Dari segi fungsionalitas kabin, konfigurasi kursi dan kemewahan material kulit serta tata suara premium menjadi daya tarik utama. Penumpang baris kedua dimanjakan dengan layar hiburan independen, pengisi daya nirkabel cepat, serta kontrol suhu kabin multi-zona mandiri. Ruang bagasi yang sangat fleksibel memberikan kapasitas maksimal untuk membawa perlengkapan liburan keluarga kelas atas.",
      "Setelah pengujian intensif sejauh 500 kilometer di berbagai kondisi jalanan perkotaan hingga jalan tanah pegunungan, kami menyimpulkan bahwa SUV Premium 2026 berhasil memberikan paket berkendara super lengkap bagi mereka yang menginginkan martabat berkendara berkelas tanpa mengorbankan ketangguhan performa sama sekali.",
    ],
    category: "Review",
    date: "May 05, 2026",
    author: "Hendri Wijaya",
    image:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800",
    readTime: "6 Menit Baca",
  },
];
